project:
  type: website
  output-dir: _site

website:
  title: "Trevor D. Ruiz"
  google-analytics: "G-H3YKZX4J88"
  page-navigation: false
  page-footer: "Updated September 2024. \u00a9 2024 Trevor Ruiz"
  favicon: 'favicon-lwr.png'
  search: false
  navbar:
    # title: false
    collapse: false
    left: 
      - text: "{{< fa envelope >}}"
        href: mailto:truiz01@calpoly.edu
      # - text: "{{< fa calendar-days >}}"
      #   href: https://calendly.com/tdruiz
      - text: "{{< ai google-scholar>}}"
        href: https://scholar.google.com/citations?user=YhlR1RkAAAAJ
      - text: "{{< ai orcid >}}"
        href: https://orcid.org/0009-0001-1452-2542
      - icon: github
        href: https://github.com/ruizt
      - text: "{{< ai cv >}}"
        href: https://drive.google.com/file/d/1RFzVbFxeWnh4I1KTCbRXbI-RCQD0W9Xp/view?usp=sharing
      
    
format:
  html:
    theme: cosmo
    css: styles.css

execute:
  freeze: auto

