project:
  type: website
  output-dir: docs

website:
  title: "Trevor D. Ruiz"
  page-navigation: false
  navbar:
    # logo: img/portrait1.jpeg
    background: light
    search: true
    left:
      - href: index.qmd
        text: About
      - teaching.qmd
      - research.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



