project:
  type: website
  output-dir: _site

website:
  title: "Trevor D. Ruiz"
  google-analytics: "G-H3YKZX4J88"
  page-navigation: false
  page-footer: "\u00a9 2024 Trevor Ruiz"
  favicon: 'favicon-lwr.png'
  search: false
  navbar:
    # title: false
    collapse: false
    left: 
      - text: "{{< ai google-scholar>}}"
        href: https://scholar.google.com/citations?user=YhlR1RkAAAAJ
      - text: "{{< ai orcid >}}"
        href: https://orcid.org/0009-0001-1452-2542
      - icon: github
        href: https://github.com/ruizt
      - text: "{{< ai cv >}}"
        href: https://tdruiz.com
      
    
format:
  html:
    theme: cosmo
    css: styles.css

execute:
  freeze: auto

