---
title: "Student projects"
editor: visual
bibliography: refs.bib
---

I'm currently developing projects that include opportunities for student contributions; more information will be posted here as these take shape. In the meantime, if you're a student and you're interested in research opportunities, please get in touch.

### Capstone projects

While at UCSB I co/led instruction of a year-long capstone[^1] in 2021-2022 and 2022-2023. The goal of the capstone was to engage undergraduate students in collaborative research. In the two years I oversaw the course we had 28 projects spanning a wide range of domain and industry applications.[^2] I had the good fortune of working with many talented students and dedicated partnering labs and companies, several of whom extended their research efforts in various ways beyond the scope of the class.

[^1]: Read the sequence description on my [teaching page](teaching.qmd#pstat197).

[^2]: A full project list can be found [here](http://ruizt.github.io/pstat197).

In 2022, two students extended a project on visualizing oceanographic data by developing outreach materials for public science education and engagement and gave a presentation on data storytelling at the sponsoring organization's annual conference [@gupta2022scrollytelling]. In 2023, two capstone groups presented their research during a poster session at the SIGKDD conference's Southern California Data Science Day --- one project used self-supervised learning to identify impact risk due to wildfires based on geography, fire, and location attributes [@umsted2023understanding], and the other explored an early detection system for identifying case onset of influenza-like illness based on biometric data from wearable devices [@rumsey2023identifying]. Another notable project from this year involved constructing 3D models of bees using photogrammetry [@spasibenko2023exploring].

