---
title: "Research"
editor: visual
bibliography: refs.bib
date: last-modified
date-format: "MMMM YYYY"
published-title: "Updated"
---

I'm interested in statistical methods for correlated and high-dimensional data with applications in life sciences. I also enjoy collaborative research projects involving applied statistical modeling.

I'm eager to include student contributors in my research and aim to work on topics/projects that create opportunities for student involvement. My current projects focus on specific applications or data analyses that would be accessible to undergraduate students but also have interesting methodological aspects and therein some potential to expand into projects suitable for graduate-level research.

## Current projects

#### Using environmental DNA to identify microbial taxa associated with marine mammal abundances

*Collaboration with Erin Satterthwaite, Michaela Alksne, Nastassia Patin, Julie Dinasquet, Brice Semmens, and others.*

*Student contributors (alphabetical order): Katherine Chan; Gabrielle Low; Nick Patrick; Samantha Ward*

This project leverages environmental metabarcoding data collected from quarterly cruises in the California current to identify microbial and microorganism ‘signatures’ of presence and abundance of large marine mammals. We utilize 16S and 18S r-RNA sequencing data obtained from ocean water samples collected at multiple depths along transects in the California current together with density estimates computed from visual sightings of common whale species along the same transects. We formulate a log-contrast-type model relating species density to relative abundances of amplicon sequence variants (ASVs) after adjusting for seasonality and environmental conditions and develop a sparse estimation procedure to identify small subsets of ASVs associated with changes in species density.

#### Modeling baseline metabolic needs of pregnant rattlesnakes from high resolution time series of body temperatures

*Collaboration with Haley Moniz (Biological Sciences, Cal Poly) and Emily Taylor (Biological Sciences, Cal Poly)*

*Student contributors (alphabetical order): Emma Reardon (biology); Nicole Yee (statistics)*

This project seeks to explore the effect of pregnancy on metabolism among rattlesnakes. Beaupre & Duvall (1998) measured oxygen consumption in male, non-pregnant female, and (early) pregnant female rattlesnakes and developed general equations for calculating resting metabolic rate given a snake's body temperature and weight. This project will leverage high-resolution time series of body temperatures collected from pregnant and non-pregnant female rattlesnakes over a period of several months to estimate metabolic rate fluctuations over time using the above-mentioned framework, and develop exploratory and statistical analyses aimed at (1) identifying metabolic differences between pregnant and non-pregnant rattlesnakes and (2) understanding temporal shifts in metabolism associated with seasonal and lifecycle factors.

#### Statistical methods for environmental genomics

*Supported by the Research, Scholarly & Creative Activities Program awarded by the Cal Poly Division of Research*

*Student contributors: Nick Patrick.*

Many ecological studies collect physical samples of water, soil, or other media in order to extract and sequence environmental DNA (eDNA) for a variety of purposes (Ruppert *et al.* 2019); often these samples are co-located space and time with additional survey measurements (*e.g.*, James *et al.* 2022). Integrating such data provides a potential means of investigating relationships between eDNA composition and ecological and environmental features across space and time, and although there are a variety of statistical methods that capture relationships between compositional (*i.e.,* genomic) and non-compositional (*i.e.,* environmental/physical/biological) variables, few facilitate adjustment of inferred relationships for covariates or dependence among observations due to spatial and temporal sampling patterns, both of which are present among ecological data. This project aims to: (1) develop a partial least squares (PLS) framework that explicitly incorporates these adjustments; (2) create, implement, and validate estimation algorithms; and (3) apply the methodology to one or more case studies.

## Publications

*Listed in reverse chronological order.*

<ol reversed>

<li>H. A. Moniz, J. H. Buck, H. L. Crowell, S. M. Goetz, **T. D. Ruiz**, S. M. Boback, E. N. Taylor (2024). Reproductive state impacts the thermal ecology of female rattlesnakes at a high-elevation site. *Under review.*</li>

<li>**T. D. Ruiz**, S. Bhattacharyya, S. C. Emerson (2023). Sparse estimation of parameter support sets for generalized vector autoregressions by resampling and model aggregation. *Under review.* \[[preprint](https://doi.org/10.48550/arXiv.2307.09684)\]</li>

<li>**T. D. Ruiz**, S. Bhattacharyya, S. C. Emerson (2022). A graphical sufficient condition for the stability of first-order log-linear Poisson generalized vector autoregressive processes. \[[preprint](https://dx.doi.org/10.2139/ssrn.4283477)\]</li>

<li>A. M. E. Ojwang, **T. D. Ruiz**, S. Bhattacharyya, S. Chatterjee, P. S. Ojiambo, D. H. Gent (2021). A general framework for spatio-temporal modeling of epidemics with multiple epicenters: application to an aerially dispersed plant pathogen. *Frontiers in Applied Mathematics and Statistics.* \[[paper](https://doi.org/10.3389/fams.2021.721352)\]</li>

<li>**T. D. Ruiz**, S. Bhattacharyya, M. Balasubramanian, K. Bouchard (2020). Sparse and low-bias estimation of high dimensional vector autoregressive models. *Proceedings of the 2nd Conference on Learning for Dynamics and Control* in *Proceedings of Machine Learning Research.* \[[paper](https://proceedings.mlr.press/v120/ruiz20a.html)\]</li>

<li>M. Balasubramanian, **T. D. Ruiz**, B. Cook, M. Prabhat, S. Bhattacharyya, A. Shrivastava, K. E. Bouchard (2020). Scaling of union of intersections for inference of granger causal networks from observational data. *IEEE International Parallel and Distributed Processing Symposium.* \[[paper](https://doi.org/10.1109/IPDPS47924.2020.00036)\]</li>

<li>**T. D. Ruiz** (2020). Estimation and sparse selection of conditional probability models for vector time series. *Oregon State University.* \[[thesis](https://ir.library.oregonstate.edu/concern/graduate_thesis_or_dissertations/k0698g13s)\]</li>

<li>**T. D. Ruiz** & C. L. Ellison (2020). Spatiotemporally coherent tensor decompositions for the analysis of trajectory data. *Engineer Research and Development Center* ERDC/GRL TN-20-3. \[[technical note](https://erdc-library.erdc.dren.mil/jspui/bitstream/11681/37355/1/ERDC-GRL%20TN-20-3.pdf)\]</li>

<li>D. H. Gent, S. Bhattacharyya, **T. D. Ruiz** (2019). Prediction of spread and regional development of hop powdery mildew: a network analysis. *Phytopathology.* \[[paper](https://doi.org/10.1094/PHYTO-12-18-0483-R)\]</li>

</ol>

## Student research

If you're interested in working with me, please get in touch. I often have opportunities associated with current projects, as well as ideas for M.S. theses and independent study under STAT400/STAT500, and am actively looking for student collaborators.

### Student works

-   K. G. Chan (2024). Using plankton eDNA to estimate whale abundances off the California coast: data integration and statistical modeling. California Polytechnic State University. \[MS thesis\]

-   S. Rumsey, E. Ho, C. Zheng, N. Setiawan, J. Park, M. Elcheikhali, T. D. Ruiz, A. Kolbeinsson, E. J. Daza (2023). Identifying case onset points for early detection of influenza-like illness. *ACM SIGKDD'23 Southern California Data Science Day.* Poster presentation. \[[abstract](https://drive.google.com/file/d/1mUdp1IfIl41d4oWxOL9ri-ZlG6rz1sf8/view?usp=share_link)\]

-   L. Umsted, J. Liu, P. Trujillo, E. Burrell, L. B. Lancheros, T. D. Ruiz, E. Noi, E. Zhou, S. Dodge (2023). Understanding and modeling human mobility response to California wildfires. *ACM SIGKDD'23 Southern California Data Science Day.* Poster presentation. \[[abstract](https://drive.google.com/file/d/1RgjaAakLtIK50k1pLrK_0GpZ18_4x5YA/view?usp=share_link)\]

-   M. Gupta, A. Adams, E. Satterthwaite, T. D. Ruiz (2022). A scrollytelling primer on hypoxia: developing a data storytelling tool to communicate ocean observing data to California citizens. *CalCOFI Conference 2022: Innovative Techniques and Novel Applications of Time Series Data to Marine Resource Management.* Contributed presentation. \[[data storytelling](https://calcofi.io/hypoxia-story/)\]
