---
title: "Student research"
editor: visual
bibliography: refs.bib
---

I'm currently developing projects that include opportunities for student contributions, many of which are collaborative; more information will be posted here as these projects take shape. If you're interested in research opportunities or have any questions about student research --- even completely general ones! --- please feel free [get in touch via email](mailto:truiz01@calpoly.edu) or [set up a meeting](https://calendly.com/tdruiz).

Please note that not all projects listed on this page are currently active.

## 2023-2024

### Modeling baseline metabolic needs of pregnant rattlesnakes from high resolution time series of body temperatures

**Project status**: proposed student project for Frost summer research program; \[[applications](https://forms.gle/uPUDvwNx857KY4Y26)\] open until March 1, 2024.

**Abstract**: This project seeks to explore the effect of pregnancy on metabolism among rattlesnakes. Beaupre & Duvall (1998) measured oxygen consumption in male, non-pregnant female, and (early) pregnant female rattlesnakes and developed general equations for calculating resting metabolic rate given a snake's body temperature and weight. This project will leverage high-resolution time series of body temperatures collected from pregnant and non-pregnant female rattlesnakes over a period of several months to estimate metabolic rate fluctuations over time using the above-mentioned framework, and develop exploratory and statistical analyses aimed at (1) identifying metabolic differences between pregnant and non-pregnant rattlesnakes and (2) understanding temporal shifts in metabolism associated with seasonal and lifecycle factors.

**Frost 2024 summer research positions**: This project will be a collaboration between biology and statistics students co-advised by biology and statistics faculty mentors. Thus, students working on this project can expect to gain experience in interdisciplinary collaboration; in addition, statistics students can expect to gain domain expertise, and biology students can expect to gain statistical expertise.

**Suggested preparation**: intermediate-level proficiency in R (STAT 331 or similar); regression analysis (STAT 334 or similar)

**Other notes**: collaboration with Haley Moniz (Biological Sciences, Cal Poly).

### Permutation inference for functional data

**Project status**: proposed student project for Frost summer research program; \[[applications](https://forms.gle/uPUDvwNx857KY4Y26)\] open until March 1, 2024.

**Abstract:** In the functional data analysis (FDA) setting, responses are continuous functions rather than scalars/vectors. In practice, functional responses are measured at a discrete resolution and must first be estimated using smoothing approximation techniques prior to data analysis. In many studies, high-resolution functional measurements are obtained on relatively few observational/experimental units, with relatively more attention given to the functional sampling resolution than to replication, effectively prioritizing response approximation quality over statistical inference. This project will explore the use of permutation inference for functional data with small sample sizes. Methods will apply permutation alternatives to standard parametric multivariate statistical tests for two-sample inference and analysis of variance to functional principal components. While this idea has been proposed in prior literature, it is relatively under-explored, leaving room for original contributions. The project will investigate performance through simulation and demonstrate applications through data analyses.

**Frost 2024 summer research positions**: Students would have some creative latitude regarding the project direction, though broadly the project will focus on how functional approximation impacts statistical power and seek to develop heuristics for application in practice. Students will leverage existing software packages for FDA in R to implement methods and carry out simulations and analyses, and can expect to gain expertise in functional data analysis, statistical computing, and methodological development.

**Suggested preparation**: intermediate-level proficiency in R (STAT 331 or similar) and multivariate analysis (STAT 419 or similar).

### Using environmental DNA to identify microbial taxa associated with marine mammal abundances

**Project status**: currently active. Additional positions available through Frost summer research program, \[[applications](https://forms.gle/uPUDvwNx857KY4Y26)\] open until March 1, 2024.

**Abstract:** This project seeks to leverage genetic metabarcoding data collected from quarterly cruises in the California current to search for microbial 'signatures' of presence and abundance of large marine mammals, with an initial focus on common species of whales. The project will involve using compositional data analysis and dimension reduction techniques to formulate a model of mammal abundance utilizing a sparse subset of microbial taxa and other covariates. There is also potential for the development of novel methodology. It is anticipated that the work will produce one or more journal publications.

**Frost 2024 summer research positions**: Students working on this project during summer will focus specifically on the development, implementation, and benchmarking of a novel algorithm for supervised dimension reduction of compositional data adjusted for covariate effects, and can expect to gain expertise in statistical computing.

**Suggested preparation:** intermediate-level proficiency in R (STAT 331 or similar); regression analysis (STAT 334 or similar) and multivariate analysis (STAT 419 or similar) preferred but not required.

**Other notes**: collaboration with Erin Satterthwaite (Sea Grant/CalCOFI/UCSD).
