---
title: "Teaching"
---

Much of my experience teaching statistics is concentrated around methods, applications, and data science, but I have broad interests. A full list of courses I've taught follows; I'm happy to share materials for instructional purposes on request.

### Cal Poly

#### **Probability theory** \[STAT425\] \[[website](https://stat425.tdruiz.com/)\]  {#stat425}

*Fall 2023*

Basic probability theory, combinatorial methods, independence, conditional and marginal probability, probability models for random phenomena, random variables, probability distributions, distributions of functions of random variables, mathematical expectation, covariance and correlation, conditional expectation.

### UC Santa Barbara

#### **Data science capstone** \[PSTAT197\] \[[website](https://pstat197.tdruiz.com/)\] {#pstat197}

*Winter 2022, Spring 2022, Fall 2022, Winter 2023, Spring 2023*

A preparatory course in data science topics and collaborative research skills (PSTAT197A/CMPSC190DD, offered fall term) and two experiential learning courses in which students work in teams on interdisciplinary projects sponsored by an external partner and advised by a technical specialist (PSTAT197B-C/CMPSC190DE-DF, offered winter and spring terms). Project teams establish a group contract outlining basic agreements pertaining to the collaboration and agree on outputs to produce for the sponsor by the end of the project -- typically software, documentation, and a presentation. The course sequence culminates with a public showcase of student work.

#### **Data science concepts and analysis** \[PSTAT100\] \[[website](https://pstat100.tdruiz.com/)\] {#pstat100}

*Spring 2021, Winter 2022, Spring 2022, Spring 2023*

A hands-on introduction to data science intended for intermediate-level students from any discipline with some exposure to probability and basic computing skills, but few or no upper-division courses in statistics or computer science. The course introduces central concepts in statistics -- such as sampling variation, uncertainty, and inference -- in an applied setting together with techniques for data exploration and analysis. Applications emphasize end-to-end data analyses.

#### **Statistical machine learning** \[PSTAT131/231\] {#pstat131}

*Winter 2021, Spring 2021*

Statistical Machine Learning is used to discover patterns and relationships in large data sets. Topics include: data exploration, classification and regression tress, random forests, clustering and association rules, building predictive models focusing on model selection, and model comparison and performance evaluation. Emphasis is on concepts, methods and data analysis, and students are expected to complete a significant class project, individual or team based, using real-world data.

#### **Regression analysis** \[PSTAT126\] {#pstat126}

*Summer 2021, Fall 2021*

A first course in linear regression for statistics majors covering both theory and applications with a strong emphasis on statistical computing and visualization techniques in R using tidyverse programming. Tools for reproducible analysis are also introduced. The course covers the linear model in matrix form, parameter estimation and interpretation, residual diagnostics, statistical inference, case influence statistics and outlier detection, common data transformations, categorical variables and interaction terms, and model selection and prediction.

#### **Probability and statistics** \[PSTAT120B\] {#pstat120b}

*Fall 2020, Winter 2021, Summer 2021, Fall 2021*

Distribution of sample mean and sample variance; t, chi-squared and F distributions; summarizing data by statistics and graphs; estimation theory for single samples: sufficiency, efficiency, consistency, method of moments, maximum likelihood; hypothesis testing: likelihood ratio test; confidence intervals.

### Oregon State University

#### **Introduction to statistical methods** \[ST351-352\] {#st351-352}

*Spring 2018, Summer 2018*

Study designs, descriptive statistics, collecting and recording data, probability distributions, sampling distributions for means and proportions, hypothesis testing and confidence intervals for means and proportions in one- and two-sample inference, and chi-square tests. 
